# Created using wingetcreate

PackageIdentifier: QNAP.QNAPJBODManager
PackageVersion: 1.1.1.0204
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://download.qnap.com/Storage/Utility/QNAPJBODManagerWindows-1.1.1.0204.exe
  InstallerSha256: C1FA01C7F94048819FE5D307569A17CD8CF81A1464338BEEFCBE3DE01D67A304
ManifestType: installer
ManifestVersion: 1.0.0
