# Created using wingetcreate

PackageIdentifier: QNAP.QNAPJBODManager
PackageVersion: 1.1.1.0204
PackageLocale: en-US
Publisher: QNAP SYSTEMS, INC.
PackageName: QNAP JBOD Manager
License: © 2019 QNAP Systems, Inc. All rights reserved.
ShortDescription: Quickly obtain the status of JBOD health, fan rotation speed, device temperature threshold and view firmware version. All device events are recorded, and desktop notifications will be sent if a system alert occurs.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
