# Created using wingetcreate

PackageIdentifier: QNAP.Qsync
PackageVersion: 5.0.1.0319
PackageLocale: en-US
Publisher: QNAP SYSTEMS, INC.
PackageName: QNAP Qsync
License: © 2015 QNAP Systems, Inc. All rights reserved.
ShortDescription: sync enables automatic file synchronization across different devices. Simply drag and drop files in the “Qsync folder,”
ManifestType: defaultLocale
ManifestVersion: 1.0.0
