# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Piriform.CCleanerPro
PackageVersion: 5.80
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: neutral
    InstallerType: nullsoft
    InstallerUrl: https://download.ccleaner.com/cctrialsetup.exe
    InstallerSha256: A546F600BF9D7FA63AF40F28FB8CB1B487A0EB40E93E6FA3E7B6B3D9ACFFFC9C
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
>>>>>>> Stashed changes
