# Created using wingetcreate

PackageIdentifier: QNAP.QVPNDeviceClient
PackageVersion: 1.2.1.1417
PackageLocale: en-US
Publisher: QNAP
PackageName: QVPN Device Client
License: Copyright (c) QNAP. All rights reserved.
ShortDescription: The QVPN Device Client is a powerful tool that allows VPN connections directly to your QNAP devices via multiple protocols including QNAP’s proprietary QBelt.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
