# Created using wingetcreate

PackageIdentifier: QNAP.QVPNDeviceClient
PackageVersion: 1.2.1.1417
Installers:
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://download.qnap.com/Storage/Utility/QNAPQVPNWindows-1.2.1.1417.exe
  InstallerSha256: F64417CDBE2B79472AB3D99F9B09E7C157A042DBF007BC84E426614BD34BC34E
ManifestType: installer
ManifestVersion: 1.0.0
