# Created using wingetcreate

PackageIdentifier: QNAP.QENCDecrypter
PackageVersion: 1.1.1.21021
PackageLocale: en-US
Publisher: QNAP SYSTEMS, INC.
PackageName: QENC Decrypter
License: ©2018 QNAP Systems, Inc. All rights reserved.
ShortDescription: Before sharing sensitive and/or confidential files from your NAS, use File Station to encrypt them into .qenc files.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
