# Created using wingetcreate

PackageIdentifier: QNAP.QuDedupExtractTool
PackageVersion: 1.1.3.21020
PackageLocale: en-US
Publisher: QNAP SYSTEMS, INC.
PackageName: QNAP QuDedup Extract Tool
License: ©2018 QNAP Systems, Inc. All rights reserved.
ShortDescription: QNAP QuDedup Extract Tool helps restore deduplicated .qdff
ManifestType: defaultLocale
ManifestVersion: 1.0.0
